### ISSUE TITLE
log.info()

### ISSUE THREAD

**Issue by jakeogh** [Sekky61/etiketa#1]
Hi, where does log.info() after the fuse_main_real() call go? I can see the output from:

https://github.com/Sekky61/etiketa/blob/main/src/main.zig#L145

but not from:

https://github.com/Sekky61/etiketa/blob/main/src/main.zig#L118

**Comment by Sekky61** [comment]
Hello,

the log prints to stdout as usual. See the demo below.

If your question is how does the program get to the `read` function, I suggest this [article](https://richiejp.com/zig-fuse-one) that inspired me to try and experiment with this library. In one sentence, the OS calls the registered functions on users request.

## Demo

Start the program and choose where to mount it:

```bash
./zig-out/bin/etiketa -f /tmp/fuse
info: Zig hello FUSE
```

From another terminal, try to read the `hello` file:

```bash
cat /tmp/fuse/hello
```

The program should output something similar to this:

```bash
info: stat: /hello
info: open: /hello
info: read: /hello,size=4096,offset=0
info: stat: /hello
info: stat: /
info: stat: /hello
info: open: /hello
info: stat: /
```

**Comment by jakeogh** [comment]
Thanks, yes, this is what I did, but on my system it forks and I get the terminal back. `pidof etiketa` exists until I umount. Perhaps a zig or FUSE version difference? TY for the link!

```
# git clone https://github.com/Sekky61/etiketa
Cloning into 'etiketa'...
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 24 (delta 6), reused 20 (delta 5), pack-reused 0
Receiving objects: 100% (24/24), 37.46 KiB | 446.00 KiB/s, done.
Resolving deltas: 100% (6/6), done.

# cd etiketa/

# zig build -Doptimize=Debug

# mkdir fuse

# ./zig-out/bin/etiketa fuse/
info: Zig hello FUSE

# ls fuse
total 0
0 drwxr-xr-x 2 root root   0 1969-12-31 17:00:00 .
0 drwxr-xr-x 8 user user 240 2024-03-29 12:37:21 ..
0 -r--r--r-- 1 root root  15 1969-12-31 17:00:00 hello

# cat fuse/hello 
Alright, mate!

# pidof etiketa
2510

# umount fuse

# ls fuse
total 0
0 drwxr-xr-x 2 user user  40 2024-03-29 12:37:21 .
0 drwxr-xr-x 8 user user 240 2024-03-29 12:37:21 ..

# pidof etiketa

# zig version
0.12.0-dev.2823+955fd65cb

# emerge sys-fs/fuse -pv | grep fuse
[ebuild   R    ] sys-fs/fuse-3.16.2:3::gentoo  USE="suid -test" 13,834 KiB
```

**Comment by Sekky61** [comment]
I see it now. I pass a `-f` flag for foreground operation. See `./zig-out/bin/etiketa --help`. I also found this [helpful, more detailed description of options](https://libfuse.github.io/doxygen/structfuse__config.html)

**Comment by jakeogh** [comment]
There it is:) I thought I had checked `-h` and only saw 2 options, but I must have been mistaken (and I just noticed you already mentioned `-f` in the demo you posted). It works beautifully.
